In [3]:
from __future__ import division
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
x = np.array([[2, 3, 5], [1, 2, 3]], np.int32)
x

array([[2, 3, 5],
       [1, 2, 3]], dtype=int32)

In [21]:
x[:1, 2]

array([5], dtype=int32)

In [20]:
x[1, 2]

3

In [28]:
x[0:15, 1]

NameError: name 'x' is not defined

In [4]:
np.arange(1, 12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
type(np.arange(1, 12))

numpy.ndarray

In [11]:
nested_array = np.arange(1, 13).reshape([4, 3])

In [15]:
z = np.matrix(nested_array)
z

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [18]:
z[1:2, 1:2] # goal is to select a submatrix of 5

matrix([[5]])

In [20]:
# goal is to select 5 6, 8 9 matrix
z[1:3, 1:3]

matrix([[5, 6],
        [8, 9]])

In [22]:
# goal is to select matrix of 3rd row
z[2:3, :]

matrix([[7, 8, 9]])

In [23]:
# select whole matrix
z[:, :]

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [30]:
np.arange(21, 0, -3).sum()

84